name = "gitpulse-api"
main = "src/index.js"
compatibility_date = "2024-03-01"

[vars]
ENVIRONMENT = "production"
PAYPAL_URL = "https://paypal.me/elbouami47"
WALLET_ADDRESS = "8sDLX3okSV974wdjdeKhN9uWLZDr45DeGCJ28zgTLEdJ"
GUMROAD_URL = "https://amygraphics.gumroad.com/l/mcp-pro"
